use_frameworks!

target 'pod_test_Example' do
#  pod 'pod_test', :path => '../'
  pod 'pod_test',:podspec => '../pod_test.podspec'

  target 'pod_test_Tests' do
    inherit! :search_paths

    
  end
end
